import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
const spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["700"],
});
import "./globals.css";

export const metadata: Metadata = {
  title: "Calculator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`theme1 ${spartan.className}`}>{children}</body>
    </html>
  );
}
